[project]
name = "ti4-draft-discord-bot"
version = "0.1.0"
description = "A Discord bot for drafting Twilight Imperium 4th Edition"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "discord.py>=2.3.2",
    "python-dotenv>=1.0.0"
]
